/* config-workspace.h.  Generated by cmake from config-workspace.h.cmake  */

/* Define if you have DPMS support */
#cmakedefine HAVE_DPMS 1

/* Define if you have the DPMSCapable prototype in <X11/extensions/dpms.h> */
#cmakedefine HAVE_DPMSCAPABLE_PROTO 1

/* Define if you have the DPMSInfo prototype in <X11/extensions/dpms.h> */
#cmakedefine HAVE_DPMSINFO_PROTO 1

/* Defines if your system has the libfontconfig library */
#cmakedefine HAVE_FONTCONFIG 1

/* Defines if your system has the freetype library */
#cmakedefine HAVE_FREETYPE 1

/* KDE's default home directory */
#cmakedefine KDE_DEFAULT_HOME "${KDE_DEFAULT_HOME}"

/* KDE's configuration directory */
#define KDE_CONFDIR "${KDE4_CONFIG_INSTALL_DIR}"

/* KDE's static data directory */
#define KDE_DATADIR "${KDE4_DATA_INSTALL_DIR}"

/* KDE's static shared data directory */
#define KDE_SHAREDIR "${KDE4_SHARE_INSTALL_PREFIX}"

/* KDE's system configuration directory */
#define KDE_SYSCONFDIR "${KDE4_SYSCONF_INSTALL_DIR}"

/* X libraries directory */
#cmakedefine XLIBDIR "${XLIBDIR}"

/* xkb resources directory */
#cmakedefine XKBDIR "${XKBDIR}"
