/* config.h.  Generated by cmake from config.h.cmake */

/* Defines if you have GL (Mesa, OpenGL, ...) */
#cmakedefine HAVE_GL 1

/* Define to 1 if you have the <memory.h> header file. */
#cmakedefine HAVE_MEMORY_H 1
