#ifndef __CONFIG_FONTINST_H__
#define __CONFIG_FONTINST_H__

#define KFONTINST_LIB_EXEC_DIR "@KDE4_LIBEXEC_INSTALL_DIR@"
#define KFONTINST_ROOT_FONTS_DIR "@KDE4_SYSCONF_INSTALL_DIR@/fonts/"
#define KFONTINST_SYSTEM_FONTS_DIR "@KDE4_SHARE_INSTALL_PREFIX@/fonts/"

#endif
